const FIRST_TITLE = "¿CREES QUE TU EMPRESA ";
const SECOND_TITLE = "ESTÁ LISTA PARA EL FUTURO?";
const CONTACT_BUTTON = "CONTÁCTANOS";
const ASK_US_HOW = "TE AYUDAMOS EN LA TRANSFORMACIÓN DIGITAL";

export { FIRST_TITLE, SECOND_TITLE, CONTACT_BUTTON, ASK_US_HOW };
